#!/bin/bash


# rm -rf dist/*
rm VERSION.tar.gz
cp setup_template.py setup.py
sed -i "s/VERSION/${1}/g" setup.py
python setup.py sdist
twine upload dist/*
tar -czv -f dist/${1}.tar.gz eloquentarduino --exclude='*.pyc'
git add .
git commit -m "bump dist to ${1}"
git push origin master -f